### ISSUE TITLE
Can't make the youtube coffee script to work.

### ISSUE THREAD

**Issue by karlalopez** [alejandrobabio/alejandrobabio.github.io#1]
Hi Alejandro,

I tried to implement your solution for youtube/jekyll on my http://karlalopez.github.io/ page but had no success. The js is generated in the right place but I'm getting an error in the console I can't figure out.

Any thoughts on how I can solve it?

Thanks!

**Comment by alejandrobabio** [comment]
Hi Karla, you need to put the youtube script after jQuery script. Just move [line 48 at footer.html](https://github.com/karlalopez/karlalopez.github.io/blob/master/_includes/footer.html#L48) to [js.html](https://github.com/karlalopez/karlalopez.github.io/blob/master/_includes/js.html#L2), after line 2 must be enough.

**Comment by karlalopez** [comment]
Thanks Alejandro, fixed and working perfectly! Happy new year!

**Comment by alejandrobabio** [comment]
You're welcome. And, Happy New Year to you too!
